// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope for client→worker messages (multiplexed by player_id)
type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	MessageType   string                 `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // "join_room", "guess", "stroke", etc.
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                            // Original JSON payload from client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameMessage) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *GameMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *GameMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Envelope for worker→client messages (broadcast or targeted)
type BroadcastMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomCode        string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	MessageType     string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`               // "player_list", "stroke", "chat_message", etc.
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                          // JSON payload to deliver to client(s)
	TargetPlayerIds []string               `protobuf:"bytes,4,rep,name=target_player_ids,json=targetPlayerIds,proto3" json:"target_player_ids,omitempty"` // Empty = all players in room
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastMessage) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *BroadcastMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BroadcastMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BroadcastMessage) GetTargetPlayerIds() []string {
	if x != nil {
		return x.TargetPlayerIds
	}
	return nil
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x12skribbl.gateway.v1\"\x84\x01\n" +
	"\vGameMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x98\x01\n" +
	"\x10BroadcastMessage\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12*\n" +
	"\x11target_player_ids\x18\x04 \x03(\tR\x0ftargetPlayerIds2f\n" +
	"\vGameService\x12W\n" +
	"\n" +
	"RoomStream\x12\x1f.skribbl.gateway.v1.GameMessage\x1a$.skribbl.gateway.v1.BroadcastMessage(\x010\x01B\x0fZ\rgateway/protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_proto_goTypes = []any{
	(*GameMessage)(nil),      // 0: skribbl.gateway.v1.GameMessage
	(*BroadcastMessage)(nil), // 1: skribbl.gateway.v1.BroadcastMessage
}
var file_game_proto_depIdxs = []int32{
	0, // 0: skribbl.gateway.v1.GameService.RoomStream:input_type -> skribbl.gateway.v1.GameMessage
	1, // 1: skribbl.gateway.v1.GameService.RoomStream:output_type -> skribbl.gateway.v1.BroadcastMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
