"""Default word list for the Pictionary game.

Contains 200+ common nouns suitable for a drawing and guessing game.
"""

WORDS = [
    "apple", "banana", "car", "dog", "elephant",
    "flower", "guitar", "house", "island", "jacket",
    "kite", "lamp", "mountain", "notebook", "ocean",
    "piano", "queen", "rainbow", "sun", "tree",
    "umbrella", "violin", "whale", "xylophone", "yacht",
    "zebra", "airplane", "bridge", "castle", "diamond",
    "eagle", "forest", "globe", "hammer", "igloo",
    "jungle", "kangaroo", "lighthouse", "moon", "nest",
    "octopus", "penguin", "quilt", "rocket", "snowflake",
    "tornado", "unicorn", "volcano", "waterfall", "window",
    "anchor", "balloon", "candle", "dragon", "envelope",
    "feather", "giraffe", "helicopter", "iceberg", "jellyfish",
    "key", "ladder", "magnet", "necklace", "owl",
    "parachute", "robot", "scissors", "telescope", "surfboard",
    "vase", "wizard", "camera", "dinosaur", "firework",
    "ghost", "helmet", "compass", "jewel", "knot",
    "lemon", "mushroom", "ninja", "orange", "pirate",
    "ring", "skull", "treasure", "vampire", "wolf",
    "arrow", "butterfly", "clock", "drum", "engine",
    "flag", "grapes", "heart", "ink", "jar",
    "king", "lion", "mirror", "nurse", "onion",
    "parrot", "rabbit", "snake", "tiger", "uniform",
    "village", "wheel", "angel", "bread", "cherry",
    "dolphin", "earth", "frog", "garden", "horse",
    "iron", "judge", "koala", "leaf", "mermaid",
    "needle", "olive", "pumpkin", "rose", "spider",
    "throne", "turtle", "suitcase", "witch", "zipper",
    "astronaut", "beach", "cactus", "dentist", "emerald",
    "fountain", "gorilla", "harp", "insect", "jigsaw",
    "kettle", "lobster", "maze", "napkin", "ostrich",
    "peacock", "radar", "satellite", "tomato", "trophy",
    "waffle", "battery", "caterpillar", "dominoes", "escalator",
    "flamingo", "grasshopper", "hammock", "icicle", "jukebox",
    "kayak", "lantern", "microscope", "newspaper", "origami",
    "pretzel", "quicksand", "scarecrow", "trampoline", "ukulele",
    "windmill", "acorn", "blanket", "crayon", "donut",
    "elevator", "fireplace", "goldfish", "horseshoe", "iguana",
    "jellybean", "keyboard", "lollipop", "mailbox", "nutcracker",
    "paintbrush", "sandwich", "toothbrush", "volleyball", "wrench",
    "backpack", "chandelier", "dragonfly", "earring", "football",
    "glasses", "hamburger", "icecream", "lanyard", "starfish",
]
