# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from backend.proto import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub:
    """GameService provides bidirectional streaming for room-level communication.
    One stream per room carries multiplexed messages for all players in that room.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RoomStream = channel.stream_stream(
                '/skribbl.gateway.v1.GameService/RoomStream',
                request_serializer=game__pb2.GameMessage.SerializeToString,
                response_deserializer=game__pb2.BroadcastMessage.FromString,
                _registered_method=True)


class GameServiceServicer:
    """GameService provides bidirectional streaming for room-level communication.
    One stream per room carries multiplexed messages for all players in that room.
    """

    def RoomStream(self, request_iterator, context):
        """Bidirectional stream: one per room.
        Gateway sends GameMessage (player actions), Worker sends BroadcastMessage (responses/broadcasts).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RoomStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RoomStream,
                    request_deserializer=game__pb2.GameMessage.FromString,
                    response_serializer=game__pb2.BroadcastMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skribbl.gateway.v1.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skribbl.gateway.v1.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService:
    """GameService provides bidirectional streaming for room-level communication.
    One stream per room carries multiplexed messages for all players in that room.
    """

    @staticmethod
    def RoomStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/skribbl.gateway.v1.GameService/RoomStream',
            game__pb2.GameMessage.SerializeToString,
            game__pb2.BroadcastMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
