# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x12skribbl.gateway.v1\"Z\n\x0bGameMessage\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x11\n\troom_code\x18\x02 \x01(\t\x12\x14\n\x0cmessage_type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"g\n\x10\x42roadcastMessage\x12\x11\n\troom_code\x18\x01 \x01(\t\x12\x14\n\x0cmessage_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x19\n\x11target_player_ids\x18\x04 \x03(\t2f\n\x0bGameService\x12W\n\nRoomStream\x12\x1f.skribbl.gateway.v1.GameMessage\x1a$.skribbl.gateway.v1.BroadcastMessage(\x01\x30\x01\x42\x0fZ\rgateway/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rgateway/proto'
  _globals['_GAMEMESSAGE']._serialized_start=34
  _globals['_GAMEMESSAGE']._serialized_end=124
  _globals['_BROADCASTMESSAGE']._serialized_start=126
  _globals['_BROADCASTMESSAGE']._serialized_end=229
  _globals['_GAMESERVICE']._serialized_start=231
  _globals['_GAMESERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
